import type { Metadata } from "next";
import {Comic_Neue, Montserrat} from "next/font/google";
import "./globals.css";

const comicNeue = Comic_Neue({
    subsets: ["latin"],
    weight: ["400", "700"], // обычный и жирный
    style: "normal",
});

const montserrat = Montserrat({
    subsets: ["latin"],
    weight: ["400", "700"], // обычный и жирный
    style: "normal",
});

export const metadata: Metadata = {
  title: "Well-Comm",
  description: "Generated by create next app",
  icons: {
    icon: '/images/favicon.ico', // Chemin vers l'image dans le dossier public/
  },
};

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode;
}) {
    return (
        <html lang="fr" className={montserrat.className}>
        <body className={comicNeue.className}>
        {children}
        </body>
        </html>
    );
}
