import type { Metadata } from "next";
import {Montserrat} from "next/font/google";
import "./globals.css";
import AuthProvider from "@/components/AuthProvider";

const montserrat = Montserrat({
    subsets: ["latin"],
    weight: ["400", "700"],
    style: "normal",
});

export const metadata: Metadata = {
    title: "Well-Comm",
    description: "Generated by create next app",
    icons: {
        icon: '/images/favicon.ico',
    },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="fr" className={montserrat.className}>
        <body>
        {/* On enveloppe les enfants (tes pages) avec la sécurité */}
        <AuthProvider>
            {children}
        </AuthProvider>
        </body>
        </html>
    );
}
